name: Get Org members

on:
  workflow_dispatch:

jobs:
  get-members:
    runs-on: ubuntu-latest

    steps:
      - name: Get Org members
        uses: actions/github-script@v6
        id: get-org-members
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            const sgFamilyMembers = await github.rest.orgs.get('sg-family')
            console.log(sgFamilyMembers)
      - name: Get result
        run: echo ${{steps.get-org-members.outputs.result}}
