name: Get Org members

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-members:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@v3
        id: get-org-members
        with:
          script: \
            const sgFamilyMembers = await github.rest.orgs.get('sg-family')
            console.log(sgFamilyMembers)
          result-encoding: json
      - name: Get result
        run: echo "${{steps.get-org-members.outputs.result}}"
